### ISSUE TITLE
Question: More details on calculation for many runners are scaling up

### ISSUE THREAD

**Issue by toast-gear** [philips-labs/terraform-aws-github-runner#1283]
Hello again 👋 

I wanted to know what controls how many runners get span up. I made the below job to test how the scaling works. Our runner group has the config of 
```
runners_maximum_count = 15
delay_webhook_event = 0
```

The bootstrap process takes about 2 minutes as for the moment as we aren't using a baked AMI.

```yaml
name: Scaling Test

on:
  workflow_dispatch:
    inputs:
      NumberOfJobsToCreate:
        description: 'Number of Jobs to Create'     
        required: true
        default: "10"

jobs:
  build-matrix:
    runs-on: default
    outputs:
      matrix: ${{ steps.matrix-json.outputs.matrix }}
    steps:
      - name: Build Matrix
        id: matrix-json
        run: |
          # Setup
          count_array=()
          # Process
          for((i=1;i<=${{ github.event.inputs.NumberOfJobsToCreate }};i++)); do
              count_array=("${count_array[@]}" "${i}")
          done
          # Output
          echo "Gandalf var : $gandalf"
          echo "Array length : ${#count_array[@]}"
          echo "Array values : ${count_array[*]}"
          echo "Constructing array into GitHub matrix"
          # Remove trailing comma without leaving a trailing space
          joined=$(printf "\"%s\"," "${count_array[@]}" | sed 's/\(.*\),/\1/')
          echo "Matrix set to :"
          echo "[$joined]"
          echo "::set-output name=matrix::[$joined]"
  scaling-jobs1:
    needs: build-matrix
    runs-on: default
    strategy:
        matrix:
          job-number: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    name: Scale Runner ${{ matrix.job-number }}
    steps:
      - name: Run Sleep
        run: |
          sleep 1s
```

We ultimately ended up with 9 runners provisioned in total. It's not an issue per se and it won't stop us from using the module, it just would be good to get a better understanding of how it calculates how many runners to spin up. I assumed it would spin up 1 per job assuming the webhook delay was set to 0.

II ran this workflow with a value of 50 jobs, I expected more than 9 runners total to be span up. Because our bootstrap time is fairly long atm and the scaling doens't seem to be a 1:1 ratio jobs get done fairly quickly as we have a minimum_running_time_in_minutes` of 10 minutes. My end goal is to get to runners as close to being single use as possible to ensure a deterministic environment.
