### ISSUE TITLE
Windows runner including the VS2019 C++ build tools

### ISSUE THREAD

**Issue by pbronneberg** [philips-labs/terraform-aws-github-runner#1553]
Hi,

I would love to start using the Windows Runners.
So, really happy to see PR #1525 by @maths22!

My toolchain requires Visual C++ (VS2019) on top of this `Windows-Core-2019` image.
As far as I know, for Windows it is not so easy to use a bare agent and install dependencies for each build. (or has this improved?)
So, I would like to build an image based on `Windows-Core-2019` and add VS2019 build tools & Windows SDKs via chocolatey packages.

Happy to bring this in a PR., but looking for some advise before I start:
* shall I add another image to enable this? (e.g. `windows-core-2019-vs2019`) Or does this specific image belong in a separate repo? 
* Are there already ideas on how to support a variety of images? (e.g. ephemeral runners, scaling out from 0 when needed)

Perhaps @ScottGuymer or @npalm will know the answer :)

Thanks!

**Comment by ScottGuymer** [comment]
I would lean towards keeping the agents as simple as possible and bring additional build tools via containers. 

Managing agents with all different kinds of dependencies is not really feasible at scale.

The con are that windows images can be large so pull times can start to factor in. There are things we can do to speed things up though.

**Comment by npalm** [comment]
The packer examples in this repository are meant as a simple example to get started to buil you rown custom AMI. In this repo I would like to keep them as simple as possible. 

@ScottGuymer The windows github action runner does not support docker. Docker is not supported via the orchestrator like you can use for docker or actions. Do you mean to run a trigger a build in docker for windows via a script?

**Comment by ScottGuymer** [comment]
No, I mean using a windows container for a job like this

```
jobs:
  containerjob:
    runs-on: [self-hosted, windows]    
    container: mcr.microsoft.com/windows/servercore:20H2

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          echo "Hello World from a windows container!"
```
