### ISSUE TITLE
Unable to set node version on windows self hosted runners

### ISSUE THREAD

**Issue by AlexShemeshWix** [philips-labs/terraform-aws-github-runner#3095]
Hi
@action@setup-node is not working on github runners based on windows-core-2022 image.
I have a workflow

```
name: Test set node
on:
  workflow_dispatch:
jobs:
  test-cross-aws:
    runs-on: [self-hosted, '${{ matrix.platform.os }}', x64, '${{ matrix.platform.label }}']
    timeout-minutes: 40
    strategy:
      matrix:
        platform: [{ os: windows, label: aws-windows-test }]
    steps:
      - name: Use Node.js
        if: always()
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'
         
      - name: check node
        run: node --version
```

This workflow will run on regular github runner, but it will fail on self-hosted runner running on windows-core-2022 image.
The error is that node command cannot be found

```
node : The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\actions-runner\_work\_temp\9d937413-9123-4683-9173-2533e8641eaf.ps1:2 char:1
+ node --version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (node:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Error: Process completed with exit code 1.
```

Looking at the code of [action/setup-node ](https://github.com/actions/setup-node/blob/a4fcaaf314b117a40d694a35ee36461f8ff3c6e6/src/distributions/official_builds/official_builds.ts#L127). I can see it uses core.addPath function that updates GITHUB_PATH with path to installed versions. 
I cannot check values of GITHUB_PATH it looks like temporary file
`D:\a\_temp\_runner_file_commands\add_path_5f4d9d96-fc62-4402-b958-75b84b364cc9`
How do i debug it?

**Comment by AlexShemeshWix** [comment]
I can even make this case more simple

```
name: Test set path
on:
  workflow_dispatch:
jobs:
  test-cross-aws:
    runs-on: [self-hosted, '${{ matrix.platform.os }}', x64, '${{ matrix.platform.label }}']
    #runs-on: windows-latest   
    strategy:
      matrix:
        platform: [{ os: windows, label: wix-aws-windows-test }]
    steps:
      - name: create fake batchfile
        if: always()
        run: |
           mkdir testfolder
           echo "@echo off" | Out-File -FilePath testfolder/testbatch.bat -Encoding utf8
           echo "echo SOMETHING" | Out-File -FilePath testfolder/testbatch.bat -Encoding utf8           

      - name: add path
        if: always()
        run: echo "$pwd\testfolder;" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: run custom binary with path
        if: always()
        run: testbatch.bat
```

Will work in github, but it wont work on self-hosted runner.
