### ISSUE TITLE
Additional runners launched

### ISSUE THREAD

**Issue by sdarwin** [philips-labs/terraform-aws-github-runner#3290]
Description of problem:

Create a github actions workflow that has a mix of self-hosted and standard jobs. Some on github's infrastructure, and others on self-hosted runners. In the example below, there are 3 self-hosted jobs and 7 which are not self-hosted.

How many terraform runners ought to be created in this situation?

You would think the answer is 3. And having `exactMatch: true` should help, right? What is the effect of exactMatch in this situation? Since regular jobs do not have a "self-hosted" label they are not an exact match.

The result can easily be replicated. Use the multi-runner example https://github.com/philips-labs/terraform-aws-github-runner/tree/main/examples/multi-runner with max count of 10, and ephemeral = true, and the workflow file below.  

(only) these modifications to examples/multi-runner:
runners_maximum_count: 10
enable_ephemeral_runners: true

.github/workflows/ci.yml

```
name: CI
on:
  pull_request:
    branches:
      - master
      - develop
      - feature/**
  push:
    branches:
      - '*'
      - '**'
jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: test1
            os: [ self-hosted, linux, x64, ubuntu-latest ]
          - name: test2
            os: [ self-hosted, linux, x64, ubuntu-latest ]
          - name: test3
            os: [ self-hosted, linux, x64, ubuntu-latest ]
          - name: test4
            os: ubuntu-latest
          - name: test5
            os: ubuntu-latest
          - name: test6
            os: ubuntu-latest
          - name: test7
            os: ubuntu-latest
          - name: test8
            os: ubuntu-latest
          - name: test9
            os: ubuntu-latest
          - name: test10
            os: ubuntu-latest
    name: ${{ matrix.name }}
    timeout-minutes: 120
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test
        shell: bash
        run: |
          echo "Running the test on ${{ matrix.os }}"
          sleep 600
          true
```

It's not very serious if these extra 7 runners start, because they ultimately don't get assigned any jobs, and then the brute force scale-down terminates the instances fairly quickly.   But still, it would be preferable if they were never launched at all, right?
