### ISSUE TITLE
v4.0.0 issues with `run.sh` jitconfig after rebuilding AMI

### ISSUE THREAD

**Issue by strophy** [philips-labs/terraform-aws-github-runner#3390]
I have a multi-runner config that specifies the following in `examples/multi-runner/templates/runner-configs/linux-x64-platform.yaml`:
```
matcherConfig:
  exactMatch: true
  labelMatchers:
    - [ self-hosted, linux, x64, ubuntu-platform ]
fifo: true
delay_webhook_event: 0
redrive_build_queue:
  enabled: false
  maxReceiveCount: null
runner_config:
  runner_os: linux
  runner_architecture: x64
  runner_extra_labels: ubuntu-platform
  runner_run_as: ubuntu
  runner_name_prefix: ubuntu-platform-x64_
...
```

Yesterday I pulled to include the v4.0.0 changes and deployed again, and now when my runners come up, they do not include the `ubuntu-platform` label I specified. The runners sit idle and do not take pending jobs until I manually select the runner and apply the label in the Settings > Actions > Runners interface on GitHub.
![image](https://github.com/philips-labs/terraform-aws-github-runner/assets/32928115/7b9bcf98-1648-451f-ae12-6bc878bcfe7d)

I've been looking through the changes in v4.0.0 and while I can see a lot of the relevant variables being renamed, I can't see exactly where this is going wrong, @GuptaNavdeep1983 can you help? Thanks in advance!
