### ISSUE TITLE
Scale down in multi runner config not working correctly after upgrading to v5.2.1

### ISSUE THREAD

**Issue by devshah1** [philips-labs/terraform-aws-github-runner#3603]
Scale down in multi runner config for org level runners is not working. I have separate runner configs for different instance types and it looks like the scale down function incorrectly passes `` value to `evaluateAndRemoveRunners` function after upgrading from v2.1.0 --> v5.2.1

There's 3 different runner configs, one for each instance type - large, xlarge and 2xlarge. Only the latter two aren't working and the configuration is exactly the same except the pool count.

I was able to find this out by adding more logs to line #152 of `scale-down.ts` to debug further. It seems like the below line doesn't return anything and that's why no instances are scaled down.

```const runners = filterRunners(ec2Runners);```

<img width="1388" alt="image" src="https://github.com/philips-labs/terraform-aws-github-runner/assets/94870799/5cfc72b9-0458-496d-ad60-e04d2af778dd">

Is there something missing on the configuration front that's causing this or is this an actual bug?

**Comment by npalm** [comment]
Can you check the multi-runner example. This example contains also some non ephemeral runners. Please also check the release 3.0.0 and 4.0.0 for breaking changes.

**Comment by devshah1** [comment]
@npalm I did check the breaking changes & the examples, however it seems like scale down isn't working for ephemeral multi-runner config with `pool_config`. Can you please take a look and test on your side?

Below is one of the runner configs, for which scale down doesn't work due to the above pasted logs.
```
matcherConfig:
  exactMatch: true
  labelMatchers:
    - [self-hosted, linux, x64, xlarge]
runner_config:
  runner_os: linux
  runner_architecture: x64
  create_service_linked_role_spot: true
  enable_ssm_on_runners: true
  enable_organization_runners: true
  enable_ephemeral_runners: true
  enable_jit_config: false
  enable_runner_detailed_monitoring: false
  delay_webhook_event: 0
  minimum_running_time_in_minutes: 5
  instance_types:
    - m7g.xlarge
    - m7gd.xlarge
    - r7gd.xlarge
    - r7i.xlarge
    - m6g.xlarge
    - m6a.xlarge
    - m6gd.xlarge
    - r6g.xlarge
  instance_allocation_strategy: capacity-optimized
  pool_runner_owner: test
  pool_config:
    - size: 80
      schedule_expression: "cron(0/2 13-21 ? * MON-FRI *)" # 9-5pm in UTC
    - size: 1
      schedule_expression: "cron(0/2 13-20 ? * SAT-SUN *)"
  idle_config:
    - idleCount: 80
      cron: "* * 9-18 * * 1-5"
      timeZone: "America/New_York"
    - idleCount: 10
      cron: "* * 19-23 * * 1-5"
      timeZone: "America/New_York"
    - idleCount: 3
      cron: "* * 0-7 * * 1-5"
      timeZone: "America/New_York"
    - idleCount: 2
      cron: "* * 8-17 * * 6-7"
      timeZone: "America/New_York"
  block_device_mappings:
    - device_name: /dev/xvda
      delete_on_termination: true
      volume_type: gp3
      volume_size: 50
      throughput: 175
      iops: 3000
      encrypted: true
      kms_key_id: null
      snapshot_id: null
  runners_maximum_count: 120

```
