### ISSUE TITLE
Matrix jobs not being picked up

### ISSUE THREAD

**Issue by PerGon** [philips-labs/terraform-aws-github-runner#3607]
We believe this issue is actually caused by GitHub other than how this module works. But I wonder if someone else faced this problem and if there's any good workaround.

Quick specs of our setup:
- Running version `v5.3.0`
- Using `ephemeral` runners
- We use `GHES 3.8.11`

(Let me know if additional info is necessary)

## Replicate the issue

The issue can be replicated with a GHA like this:
```
name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: [ self-hosted, test-ubuntu ]
    strategy:
      max-parallel: 1
      matrix:
        index: [0,1,2,3,4,5,6,7,8,9]
    steps:
      - run: |
          echo "Index ${{ matrix.index }}"
          echo "Sleeping 10 minutes"
          date
          sleep 600
          date
```

### Observations

What we have observed is that GitHub will send the `queue` events all at once (see screenshot below), but because `max-parallel` won't allow all jobs to run at once. So jobs will run in sequence.
But because all `queue` events are sent in one go, the EC2 instances will be booted up immediately (even tho they can't pick up the jobs). After a few minutes of all 10 instances being booted, they will be terminated for being stale. This means that when the jobs are eventually ready to be executed, there are no EC2 runners available.
![image](https://github.com/philips-labs/terraform-aws-github-runner/assets/725020/42b61b4f-ee3d-4df1-9c6c-438763b64525)

In the end, the matrix looks something like this:

![image](https://github.com/philips-labs/terraform-aws-github-runner/assets/725020/fc545a5f-7928-4130-9831-7416ea9b7cf4)

#### Timeline representation

![image](https://github.com/philips-labs/terraform-aws-github-runner/assets/725020/a494698a-5ba1-4cfd-bf44-6b5911b14ccb)

## Similar action that doesn't have the same problem

This GHA is similar, but doesn't have the same issue, as GH will only send the `queue` event when each job is meant to actually be executed (not all at once).

```
name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test01:
    runs-on: [ self-hosted, test-ubuntu ]
    steps:
      - run: |
          sleep 600
  test02:
    runs-on: [ self-hosted, test-ubuntu ]
    needs: [test01]
    steps:
      - run: |
          sleep 600
  test03:
    runs-on: [ self-hosted, test-ubuntu ]
    needs: [test02]
    steps:
      - run: |
          sleep 600
  test04:
    runs-on: [ self-hosted, test-ubuntu ]
    needs: [test03]
    steps:
      - run: |
          sleep 600
  test05:
    runs-on: [ self-hosted, test-ubuntu ]
    needs: [test04]
    steps:
      - run: |
          sleep 600
```

We have opened a ticket with GitHub asking some clarification if the way the webhook calls are handled is intended. But I'm wondering if someone else has faced this issue and if there is any strategy in this module to handled this sort of problem.

Thanks!
