### ISSUE TITLE
Clear working directory between runs?

### ISSUE THREAD

**Issue by TaxBusby** [philips-labs/terraform-aws-github-runner#3854]
Hi there, I'm using the non-ephemeral runners, which is fine with me for performance/isolation tradeoff.

However, it looks like the working directory given to workflows does not get cleared between jobs. This can lead to surprise for developers who expect a clean working directory.

Is there an option available to have the runners clear the working directory between runs?

--- 

Here's a short workflow I'm using to test this case:

```yaml
name: Ephemerality Test
on:
  workflow_dispatch:

jobs:
  write:
    runs-on: [self-hosted]
    name: Write
    steps:
      - name: Write files
        run: |
          echo Current Directory: $(pwd)
          ls
          echo "Local File Exists" > hello.txt
          echo "Temp File Exists" > /tmp/hello.txt
          
  read:
    runs-on: [self-hosted]
    needs: [write]
    name: Read
    steps:
      - name: Test for persisted files
        run: |
          echo Current Directory: $(pwd)
          ls
          cat hello.txt || echo "Local dir cleared"
          cat /tmp/hello.txt || echo "Tmp dir cleared"
          
          if [ -f hello.txt ]; then
              echo "Local file was not cleared!"
              exit 1
          fi
          if [ -f /tmp/hello.txt ]; then
              echo "Temp file was not cleared!"
              exit 1
          fi
```

Outputs:

```
// Write
Current Directory: /opt/actions-runner/_work/gh-self-hosted-runners/gh-self-hosted-runners
hello.txt

// Read
Current Directory: /opt/actions-runner/_work/gh-self-hosted-runners/gh-self-hosted-runners
hello.txt
Local File Exists
Temp File Exists
Local file was not cleared!
```
